### ISSUE TITLE
Docking Station in Data Collection Office only supports 3/5 docs at a time

### ISSUE THREAD

**Issue by Eric-Dorflinger** [Plantiga/FirmwareDockerBase#7]
When charging pods on our docking station it will only support up to 3 pods at a time, regardless of which docks you are putting the pods on.

P.S. Since we don't have to worry about this with customers it doesn't have to be fixed, but just an FYI

**Comment by ahollist** [comment]
Hey Eric, this is the repository for our Docker image, not the docks. This issue is better posted on the https://github.com/Plantiga/hw-Plantiga_Osensa repository for hardware.

**Comment by Eric-Dorflinger** [comment]
@ahollist Hey Andrew, not sure if I see a repository for hardware, the page you linked gives a 404 error.

**Comment by ahollist** [comment]
No worries, I had a chat with Sean, I'll update the data team on where we want to report bugs from here on out!
